services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: collect_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: collect_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddd_laravel
      MYSQL_USER: ghostg
      MYSQL_PASSWORD: ghostG2025@
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  dbdata:
